-- Exercice 0.14.1 : Merge, Returning et sous-requête corrélée

-- 1. Modifiez la structure de la table pour mettre en place une séquence ou une auto incrémentation du numéro employé pour les futures insertions
CREATE SEQUENCE SEQ_EMPLOYE START WITH 1; -- Ajustez le START WITH selon le dernier ID

ALTER TABLE employes 
ALTER COLUMN no_employe SET DEFAULT nextval('SEQ_EMPLOYE');
-- MYSQL/MariaDB
ALTER TABLE employes 
MODIFY COLUMN no_employe INT AUTO_INCREMENT;
-- ORACLE versions 12c+
ALTER TABLE employes 
MODIFY (no_employe GENERATED BY DEFAULT AS IDENTITY);
-- 2. Insérez et retournez le numéro de l’employé Sarah Mendes embauché aujourd’hui
-- L'employé Chen Amandine avait quitté l’entreprise il y a quelques mois, vous ne pouvez pas exécuter une requête SELECT pour vérifier si elle est toujours présente dans la table des employés. Insérez à nouveau cet employé ou mettez à jour ses informations :
-- - Date de naissance 18/09/1996
-- - Poste Responsable DSI
-- - Salaire 7200€
/* =========================================================
INSERTION SARAH MENDES
========================================================= */
INSERT INTO employes (prenom, nom, date_embauche)
VALUES ('Sarah', 'Mendes', CURRENT_DATE)
RETURNING no_employe;
-- MySQL
INSERT INTO employes (prenom, nom, date_embauche)
VALUES ('Sarah', 'Mendes', CURRENT_DATE());
SELECT LAST_INSERT_ID();-- récupération du dernier ID inseré
-- ORACLE
INSERT INTO employes (prenom, nom, date_embauche)
VALUES ('Sarah', 'Mendes', SYSDATE)
RETURNING no_employe INTO :v_no_employe; -- (:v_no_employe est une variable de session)
/* =========================================================
INSERTION OU MODIFICATION AMANDINE CHEN
========================================================= */
-- Oracle
MERGE INTO employes e
USING (SELECT 'Amandine' AS prenom, 'Chen' AS nom FROM dual) src
ON (e.prenom = src.prenom AND e.nom = src.nom)
WHEN MATCHED THEN
  UPDATE SET e.date_naissance = TO_DATE('1996-09-18', 'YYYY-MM-DD'),
             e.fonction = 'Responsable DSI',
             e.salaire = 7200
WHEN NOT MATCHED THEN
  INSERT (prenom, nom, date_naissance, fonction, salaire)
  VALUES (src.prenom, src.nom, TO_DATE('1996-09-18', 'YYYY-MM-DD'), 'Responsable DSI', 7200);
-- PostgreSQL
INSERT INTO employes (prenom, nom, date_naissance, fonction, salaire)
VALUES ('Amandine', 'Chen', '1996-09-18', 'Responsable DSI', 7200)
ON CONFLICT (prenom, nom) 
DO UPDATE SET 
    date_naissance = EXCLUDED.date_naissance,
    fonction = EXCLUDED.fonction,
    salaire = EXCLUDED.salaire;
-- MySQL/MariaDB
INSERT INTO employes (prenom, nom, date_naissance, fonction, salaire)
VALUES ('Amandine', 'Chen', '1996-09-18', 'Responsable DSI', 7200)
ON DUPLICATE KEY UPDATE 
    date_naissance = VALUES(date_naissance),
    fonction = VALUES(fonction),
    salaire = VALUES(salaire);